apiVersion: v1
kind: Service
metadata:
  name: bootcamp-html
  namespace: prod
spec:
  selector:
    app: bootcamp-html
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001
    protocol: TCP